name: CD

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Application
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}  # Store your EC2 IP in GitHub Secrets
          username: ubuntu  # Default user for AWS EC2
          key: ${{ secrets-key.EC2_PRIVATE_KEY }}  # Store your private key in GitHub Secrets
          script: |
            cd ~/fastapi-book-project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi